// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
// This file was generated by Prisma
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
     // point to your seed script
    seed: "ts-node prisma/seed.ts",
  },
  datasource: {
    url: process.env.DATABASE_URL!,
  },
});